# Generated by Django 5.0.7 on 2024-08-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
